package officePractice;

/* 
 * PORTWARE DISCLAIMER 
 * COPYRIGHT (C) 2019 PORTWARE LLC. ALL RIGHTS RESERVED. 
 * 
 * THIS SOURCE CODE AND/OR DOCUMENTATION IS THE CONFIDENTIAL AND PROPRIETARY 
 * INFORMATION OF PORTWARE,LLC. ("CONFIDENTIAL INFORMATION"). YOU SHALL  NOT 
 * DISCLOSE SUCH CONFIDENTIAL INFORMATION AND SHALL USE IT ONLY IN ACCORDANCE 
 * WITH THE TERMS OF THE LICENSE AND/OR NON-DISCLOSURE AGREEMENT YOU ENTERED 
 * INTO WITH PORTWARE. 
 * 
 * THIS PROGRAMMING CODE IS INTENDED FOR ILLUSTRATIVE PURPOSES ONLY. PORTWARE 
 * MAKES NO REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS OR IMPLIED, ABOUT 
 * THE SUITABILITY OF THE CODE FOR PRODUCTION. THIS INCLUDES, BUT IS NOT 
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT 
 * AND FITNESS FOR A PARTICULAR PURPOSE. PORTWARE SHALL NOT BE LIABLE FOR ANY 
 * DAMAGES SUFFERED AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THIS CODE 
 * OR ITS DERIVATIVES. 
 */

public class DependentClass {
static {
  System.out.println("B");
}
}
